--- pystring-1.1.4/Makefile.orig	2022-12-13 20:44:27.746817243 +0100
+++ pystring-1.1.4/Makefile	2022-12-13 20:46:08.120620496 +0100
@@ -1,5 +1,7 @@
 LIBTOOL ?= libtool
-LIBDIR ?= /usr/lib
+PREFIX ?= /usr
+INCLUDEDIR ?= ${PREFIX}/include/pystring
+LIBDIR ?= ${PREFIX}/lib
 CXX ?= g++
 CXXFLAGS ?= -g -O3 -Wall -Wextra -Wshadow -Wconversion -Wcast-qual -Wformat=2
 
@@ -12,7 +14,8 @@
 	$(LIBTOOL) --mode=link --tag=CXX $(CXX) -o $@ $< -rpath $(LIBDIR)
 
 install: libpystring.la
-	$(LIBTOOL) --mode=install install -c $< $(LIBDIR)/$<
+	$(LIBTOOL) --mode=install install -Dm755 $< $(DESTDIR)$(LIBDIR)/$<
+	$(LIBTOOL) --mode=install install -Dm644 pystring.h $(DESTDIR)$(INCLUDEDIR)/pystring.h
 
 clean:
 	$(RM) -fr pystring.lo pystring.o libpystring.la .libs
